### ISSUE TITLE
Edit Education Bug

### ISSUE THREAD

**Issue by Oliviads00** [dearjeah/dayangsurga-macro#75]
Ga bisa update setelah edit tpi di instituion view nya doang

**Comment by audreyachang** [comment]
Kalau edit education, dalam edit form jadi ada "Optional(GPA)", kalau di save value GPA jadi Optional(0.0)

**Comment by Oliviads00** [comment]
bug audrey dah ketemu

**Comment by dearjeah** [comment]
institution done
